// <auto-generated />
namespace E_Recarga.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UsersWithRolesConstructor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UsersWithRolesConstructor));
        
        string IMigrationMetadata.Id
        {
            get { return "201912111258254_UsersWithRolesConstructor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
